version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-75-231-215.eu-west-1.compute.amazonaws.com
            database: dfge6ka4vf6f7q
            schema: public
            user: jyoicxdbrcagfx
            password: 313db557e475c0865603e2241de0609fc584a1abf2ec8d69b14226f1e5e8ce67
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true